[package]
name = "upload-server"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "upload-server"
path = "src/main.rs"

[dependencies]
rocket = "0.5.0-rc.3"
rocket-multipart-form-data = "0.10.5"
tokio = { version = "1" }
